### ISSUE TITLE
初始化后登录不成功

### ISSUE THREAD

**Issue by gggso** [walle233/laf-rbac-admin#2]
初始化后登录不进去....提示密码错误....我看了下登录方法..没太看懂怎么校验的密码
`  const { data: admin} = await db.collection('admin')
    .where({ username, password: hashPassword(password) })
    .getOne()
`
`function hashPassword(content: string): string {
  return crypto
    .createHash('sha256')
    .update(content)
    .digest('hex')
}`

**Comment by walle233** [comment]
抱歉，查询暂时查的是admin当前表的password，但是初始化的时候没有在admin表加上password字段，修复了这个问题，可以把表删了重新初始化哈。
密码校验 其实就是拿用户名和解密过的密码这两个条件去admin表里查，能查到就是通过

**Comment by gggso** [comment]
> 

我以为laf 有什么特殊的联查方式....琢磨半天没看懂....

**Comment by walle233** [comment]
我的锅，目前还比较粗糙，我会继续完善优化，欢迎继续提出问题哈
