### ISSUE TITLE
登录的时候不成功

### ISSUE THREAD

**Issue by xungegeblue** [walle233/laf-rbac-admin#3]
作者大大，我看初始化数据哪里是吧密码单独存放在一个password的集合里面。
登录的时候没有关联查询，直接查询admin集合了。而admin集合缺少password字段。

**Comment by walle233** [comment]
抱歉，是的查询暂时查的是admin当前表的password，但是初始化的时候没有在admin表加上password字段，修复了，可以把表删了重新初始化哈。

**Comment by xungegeblue** [comment]
感谢大佬

**Comment by walle233** [comment]
感谢使用，目前还有点粗糙，我会继续完善
